---

- name: get ec2 instance information
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ ec2_vpc_id }}"
  register: ec2_instances
  when:
    - nodes is defined

- name: terminate instances
  amazon.aws.ec2_instance:
    region: "{{ ec2_region }}"
    state: "absent"
    instance_ids: "{{ _instance_ids }}"
  when:
    - ec2_instances.instances | map(attribute='instance_id') | list | length > 0
    - _instance_ids | length > 0
  vars:
    query: "[?contains(`{{ nodes_tag_names }}`, tags.Name)].instance_id"
    _match_nodes: "{{ ec2_instances.instances | json_query(query) | list }}"
    _instance_ids: "{{ (ansible_play_hosts | map('extract',hostvars,'ec2_id') | list) | intersect(_match_nodes) | list }}"