---
- name: Create or destroy EC2 instances
  ec2_instance:
    name: "{{ ec2_name_prefix }}-{{ item.pod_name | default('') }}-{{ item.role }}-{{ item.name }}"
    key_name: "{{ ec2_key_name }}"
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    instance_type: "{{ item.instance_type }}"
    security_group: "{{ ec2_security_group }}"
    network:
      assign_public_ip: true
      source_dest_check: "{{ item.network_source_dest_check | default(omit) }}"
      private_ip_address: "{{ (item.networks | map(attribute='ip') | list)[0] if (item.networks is defined and (item.networks | length > 0)) else omit }}"
      private_ip_addresses: "{{ (item.networks | map(attribute='ip') | list)[1:] if (item.networks is defined and (item.networks | length > 1)) else omit }}"
      subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    image_id: "{{ item.image }}"
    tags:
      environment: "{{ environment | default('') }}"
      role: "{{ item.role }}"
      app: "{{ item.app_name }}"
      pod: "{{ item.pod_name | default('') }}"
      user: "{{ current_user | default('') }}"
      Contact: "{{ current_user  | default('') }}"
      AlwaysUp: "{{ item.always_up | default('false') }}"
      DeleteBy: "{{ item.delete_by | default(delete_by_date) }}"
    wait: "{{ ec2_wait }}"
    user_data: "{{ item.user_data | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
  loop: "{{ nodes }}"
  register: ec2_jobs
  async: 7200
  poll: 0
  tags:
    - always
    - provision