---

- include_tasks: preflight_check.yml
  run_once: yes

- include_tasks: provision.yml
  run_once: yes
  when: role_action == 'provision'

- include_tasks: deprovision.yml
  run_once: yes
  when: role_action == 'deprovision'