---

# this seems to be needed as ansible_password is not passed into the loop
- name: set ansible password
  set_fact:
    ansible_password: "{{ ansible_password | default('') }}"
  no_log: true

- name: grab information about AWS user
  aws_caller_info:
    region: "{{ ec2_region }}"
  register: whoami

- name: save username of AWS user
  set_fact:
    current_user: '{{ whoami.arn.split("/")[-1] }}'

- block:
    - name: delete by date (GNU)
      set_fact:
        delete_by_date: "{{ 'NEVER' if never_delete else lookup('pipe','date -d \"+{{ days_to_keep }} Days\" +%m.%d.%Y') }}"
  rescue:
    - name: delete by date (other)
      set_fact:
        delete_by_date: "{{ 'NEVER' if never_delete else lookup('pipe','date -v +{{ days_to_keep }}d +%m.%d.%Y') }}"